### ISSUE TITLE
Improve/Fix Bag panel style

### ISSUE THREAD

**Issue by OpenHogwarts** [OpenHogwarts/hogwarts#13]
Bag panel should be screen responsive like the other panels.

**Comment by kardall** [comment]
Just to let you know, I forked this, and I am redoing the Inventory system, as there are many ways to do inventory now compared to 4.6 via the UI changes. Using a Grid Layout for bag, and attempting to re-write the entire thing from scratch, since it took me an hour to dig through the existing code just to find out that half the stuff is obsolete anyway :D 

So ya, I was turn towards this project from a fellow programmer, and I am currently working on a game myself. I don't know how much I'll be here but .. I'll give it as much attention as I can. So long as I can meet my own deadlines/goals for my personal project lol.

**Comment by OpenHogwarts** [comment]
¡Thank you for spending some of your time upgrading that part!

You could have posted asking for where was the code located :)

Hope your personal project goes gold ;)
