### ISSUE TITLE
Can't  open  the  game

### ISSUE THREAD

**Issue by YingXiuHe** [OpenHogwarts/hogwarts#31]

**Comment by YingXiuHe** [comment]
When I hit the start button from Game tab,and  "SpeedTree materials need to be regenerated
"
![screenshot from 2017-10-26 16-31-40](https://user-images.githubusercontent.com/26650060/32042838-87c1cb54-ba6b-11e7-9c08-2432ff9bdebd.png)

**Comment by OpenHogwarts** [comment]
Unity version & subscription?

**Comment by harrypotterfan88** [comment]
Hi there! I seem to have a similar issue. My OS is Win10 (64-bit). I have initially downloaded the latest Unity version and it didn't work. I deleted it and then downloaded Unity version 5.4.2 (Unity DownloadAssistant -5.4.2f2) and signed up for free (trial). 

I run Unity -> Open -> select the "hogwarts-master" folder-> Your project was last opened with a different setup of Unity warning-> Continue-> Waiting forever for Calculating asset hashes, Importing small assets, etc-> Finally it opened with the "A tree couldn't be loaded because the prefab is missing." error and hundreds more. When I hit the play button, it says "All compiler errors have to be fixed before you can enter play mode."

Maybe I'm doing something wrong, but I can't find this (double click MainMenu (Assets -> Scenes -> MainMenu). I only have the Assets tab in the software, next to Edit and GameObject.

PS: Not that it isn't obvious at this point, but I have no idea about programming, and the most complicated thing I ever did game-related was copying the crack to the right folder. Still, I would really love to play this game!
![untitled](https://user-images.githubusercontent.com/33429412/32458195-458a1594-c334-11e7-9ef7-32867f34d0b6.png)

**Comment by OpenHogwarts** [comment]
It won't work with older Unity versions because on each upgrade, Unity changes how some things are declared.
I've tried to run the game and i didn't have any problem : s (Unity 2017.1.1f1)

**Comment by harrypotterfan88** [comment]
I ran the game with the latest unity version and I've had similar issues. That's what I'm saying.

**Comment by Ezaco** [comment]
I had this issue to. To fix it:

Download Unity 2017.1.1f1.
Download a new file of Open Hogwarts
Open the freshly downloaded file in Unity 2017.1.1f1

**Comment by OpenHogwarts** [comment]
@Ezaco  @harrypotterfan88  did you guys try to close and reopen the entire project after getting this errors?

**Comment by Ezaco** [comment]
I did, yes. The only way if worked for me (back when I posted) was to download the specific version of Unity and reopen the entire project.
